server {
    listen 80;
    listen [::]:80;
    server_name localhost 192.168.1.100 mephi-2026.domain.local;

    root /data/mephi-web;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/mephi-web-access.log;
    error_log  /var/log/nginx/mephi-web-error.log;
}
